;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	autopair-insert-or-skip-quote
	autopair-skip-close-maybe
	ido-switch-buffer
	kill-region
	mouse-select-window
	mouse-set-region
	paredit-forward-kill-word
	repeat
	))

(setq mc/cmds-to-run-once
      '(
	TeX-insert-backslash
	autopair-insert-opening
	mouse-minor-mode-menu
	))
